### ISSUE TITLE
[Bug Report] docker cannot start

### ISSUE THREAD

**Issue by hsuyelin** [chu-shen/BangumiKomga#11]
Traceback (most recent call last):
  File "refreshMetadata.py", line 6, in <module>
    from tools.env import *
  File "/app/tools/env.py", line 3, in <module>
    from config.config import *
ModuleNotFoundError: No module named 'config.config'
Traceback (most recent call last):
  File "refreshMetadata.py", line 6, in <module>
    from tools.env import *
  File "/app/tools/env.py", line 3, in <module>
    from config.config import *
ModuleNotFoundError: No module named 'config.config'
Traceback (most recent call last):
  File "refreshMetadata.py", line 6, in <module>
    from tools.env import *
  File "/app/tools/env.py", line 3, in <module>
    from config.config import *
ModuleNotFoundError: No module named 'config.config'
Traceback (most recent call last):
  File "refreshMetadata.py", line 6, in <module>
    from tools.env import *
  File "/app/tools/env.py", line 3, in <module>
    from config.config import *
ModuleNotFoundError: No module named 'config.config'

**Comment by chu-shen** [comment]
没有挂载`config.py`？

https://github.com/chu-shen/BangumiKomga?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
