### ISSUE TITLE
脚本执行错误

### ISSUE THREAD

**Issue by wolfling45** [chu-shen/BangumiKomga#7]
我这里出现了脚本执行错误的问题
Traceback (most recent call last): File "refreshMetadata.py", line 268, in <module> refresh_metadata(FORCE_REFRESH_LIST) File "refreshMetadata.py", line 91, in refresh_metadata komga_metadata = processMetadata.setKomangaSeriesMetadata( File "C:\Users\wolfl\gitku\BangumiKomga\processMetadata.py", line 182, in setKomangaSeriesMetadata subjectRelations = bgm.get_related_subjects(bangumiMetadata['id']) TypeError: list indices must be integers or slices, not str

我的貌似是bgv库的问题
2024-02-25 11:16:47,396 - root - ERROR - bangumiApi.py : 121 - An error occurred: 404 Client Error: Not Found for url: https://api.bgm.tv/v0/subjects/128817

我也不知道这是哪本书，有没有办法跳过指定书籍的识别?

另外，我的BANGUMI_ACCESS_TOKEN已经填好了，是不是我的账号权限不够？注册可能只有一个月。
还有就是，这个错误会一直再，重复执行多次，查看日志都是停在这里。

**Comment by chu-shen** [comment]
是

没法复现，失败的书籍会被记录到数据库，是不是把 [RECHECK_FAILED_SERIES](https://github.com/chu-shen/BangumiKomga?tab=readme-ov-file#%E5%85%B6%E4%BB%96%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E) 设置为`True`了？

错误不用管，只要脚本最后提示执行完成就行。不是的话发完整日志，不清楚第一个错误是哪个书籍造成的

另外，手动指定元数据请按照[指示操作](https://github.com/chu-shen/BangumiKomga?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%AD%A3%E9%94%99%E8%AF%AF%E5%85%83%E6%95%B0%E6%8D%AE)

**Comment by wolfling45** [comment]
RECHECK_FAILED_SERIES确实设成True，有错的我先强制刷新吧。感谢作者解答了。

**Comment by wolfling45** [comment]
我找朋友借了个账号，换了BANGUMI_ACCESS_TOKEN，现在即使打开RECHECK_FAILED_SERIES也不报错了，能看到成功的日志，感谢作者
